pipeline {
    agent any

    environment {
        DOCKER_FRONTEND_IMAGE = "vladfu/test-docker-front"
        DOCKER_BACKEND_IMAGE = "vladfu/test-docker-back"
        GIT_URL = "https://github.com/GaiShukrun/Kupot_Gemel.git"
        BUILD_NUMBER = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: "${GIT_URL}", branch: 'main'
            }
        }

        stage('Build') {
            parallel {
                stage('Build Frontend') {
                    steps {
                        dir('.') {
                            sh "docker build -t ${DOCKER_FRONTEND_IMAGE}:${BUILD_NUMBER} ."
                        }
                    }
                }
                stage('Build Backend') {
                    steps {
                        dir('MongoDB') {
                            sh "docker build -t ${DOCKER_BACKEND_IMAGE}:${BUILD_NUMBER} ."
                        }
                    }
                }
            }
        }

        stage('Tests') {
            steps {
                dir('.') {
                    sh "docker run --rm ${DOCKER_FRONTEND_IMAGE}:${BUILD_NUMBER} npm test"
                }
            }
        }

        stage('Clean up') {
            steps {
                sh "docker rmi ${DOCKER_FRONTEND_IMAGE}:${BUILD_NUMBER}"
                sh "docker rmi ${DOCKER_BACKEND_IMAGE}:${BUILD_NUMBER}"
            }
        }
    }

    post {
        always {
            sh 'docker image prune -f'
        }
    }
}
